### ISSUE TITLE
JPA Build Time Enhancement gives errors.

### ISSUE THREAD

**Issue by TomCools** [Joengenduvel/toStringVerifier#1]
For JPA to work, the entity must be enhanced. Two ways to do this are:
- Subclassing/proxies: Entity is subclassed and gets extra fields to manage the state;
- Compile/Runtime bytecode weaving: Extra fields get added to the class at compile/runtime;

The first is not an issue, because you test a class (you don't care much about subclasses for the ToString()); The bytecode weaving is an issue, because it adds extra fields during compile time.

Example of the fields OpenJPA adds when using it's byte-weaving operation mode (default):

```
private static Class pcPCSuperclass;
protected transient boolean pcVersionInit;
protected transient StateManager pcStateManager;
private transient Object pcDetachedState;
```

Since i don't think they should be considered when verifying your ToString... i would suggest to either:
- Add these fields to the list of fields to ignore, easy to do.
- Make the list of fields to ignore configurable somehow.

**Comment by Joengenduvel** [comment]
I will make the fields configurable on 2 levels.
A general level for fields that are added by frameworks at runtime.
A per call level to make it possible to have a toString method that does not contain all the fields.
