### ISSUE TITLE
ToStringVerifier doesn't work with Jacoco.

### ISSUE THREAD

**Issue by TomCools** [Joengenduvel/toStringVerifier#2]
Dear,

The *_ToStringVerifier *_ is great, but it doesn't work when running code analysis on it. $jacoco field is added by the runner and this field is not ignored by default.

Example Tests in error (classes obfuscated): 
 validateToString(b.i.a.p.r.RequestTest): Could not find field '$jacocoData' in RequestTest (httpVerb=aHTTPVerb, uri=anUri, applicationName=anApplicationName)' for class 'class b.i.a.p.r.RequestTest’

Kind regards,
Tom

**Comment by Joengenduvel** [comment]
it does. you can exclude properties on every call and by configuration by providing a properties file on the classpath: https://github.com/Joengenduvel/toStringVerifier/blob/master/test/main/resources/be.joengenduvel.tostring.properties
